spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatdb
    username: chat
    password: chat123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # options: create | update | validate | none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
  flyway:
    enabled: false
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#flyway:
#enabled: true
#locations: classpath:db/migration
#app:
#jwt:
#issuer: chat-app
#secret: change-me
#expirationMinutes: 43200 # 30 days
#media:
#root: uploads
